 language: python
 python:
    - "2.7"
 
 # Cache PlatformIO packages using Travis CI container-based infrastructure
 sudo: false
 cache:
    directories:
        - "~/.platformio"
 
 env:
    - PLATFORMIO_CI_SRC=examples/CustomKeypad/CustomKeypad.ino
    - PLATFORMIO_CI_SRC=examples/DynamicKeypad/DynamicKeypad.ino
    - PLATFORMIO_CI_SRC=examples/DynamicKeypadStated/DynamicKeypadStated.ino
    - PLATFORMIO_CI_SRC=examples/EventKeypad/EventKeypad.ino
    - PLATFORMIO_CI_SRC=examples/EventKeypadStated/EventKeypadStated.ino
    - PLATFORMIO_CI_SRC=examples/HelloKeypad/HelloKeypad.ino
    - PLATFORMIO_CI_SRC=examples/HelloKeypad3/HelloKeypad3.ino
    - PLATFORMIO_CI_SRC=examples/loopCounter/loopCounter.ino
    - PLATFORMIO_CI_SRC=examples/MultiKey/MultiKey.ino
    - PLATFORMIO_CI_SRC=examples/MultiKeyStated/MultiKeyStated.ino
    
 install:
    - pip install -U platformio
 
 script:
    - platformio ci --lib="." --board=megaatmega2560 --board=atmegangatmega168 --board=uno
